package com.samasa.hspms.guest.Entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GuestAccountDocAttachment generated by hbm2java
 */
@Entity
@Table(name = "guest_account_doc_attachment", catalog = "hs_pmsm")
public class GuestAccountDocAttachment implements java.io.Serializable {

	private GuestAccountDocAttachmentId id;
	private GuestAccount guestAccount;
	private byte[] guestDocFileId;

	public GuestAccountDocAttachment() {
	}

	public GuestAccountDocAttachment(GuestAccountDocAttachmentId id, GuestAccount guestAccount, byte[] guestDocFileId) {
		this.id = id;
		this.guestAccount = guestAccount;
		this.guestDocFileId = guestDocFileId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unitCode", column = @Column(name = "unit_code", nullable = false, length = 5)),
			@AttributeOverride(name = "guestUid", column = @Column(name = "guest_uid", nullable = false)),
			@AttributeOverride(name = "guestDocType", column = @Column(name = "guest_doc_type", nullable = false, length = 3)),
			@AttributeOverride(name = "guestDocExpiry", column = @Column(name = "guest_doc_expiry", nullable = false, length = 10)) })
	public GuestAccountDocAttachmentId getId() {
		return this.id;
	}

	public void setId(GuestAccountDocAttachmentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "guest_uid", nullable = false, insertable = false, updatable = false)
	public GuestAccount getGuestAccount() {
		return this.guestAccount;
	}

	public void setGuestAccount(GuestAccount guestAccount) {
		this.guestAccount = guestAccount;
	}

	@Column(name = "guest_doc_file_id", nullable = false)
	public byte[] getGuestDocFileId() {
		return this.guestDocFileId;
	}

	public void setGuestDocFileId(byte[] guestDocFileId) {
		this.guestDocFileId = guestDocFileId;
	}

}
