package com.samasa.hspms.guest.Entity;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GuestAccountIdentity generated by hbm2java
 */
@Entity
@Table(name = "guest_account_identity", catalog = "hs_pmsm")
public class GuestAccountIdentity implements java.io.Serializable {

	private GuestAccountIdentityId id;
	private GuestAccount guestAccount;
	private Date issueDate;
	private String issuePlace;
	private Date expiryDate;
	private String idNo;
	private String idTitle;
	private String idFirstName;
	private String idLastName;
	private String idMiddleName;

	public GuestAccountIdentity() {
	}

	public GuestAccountIdentity(GuestAccountIdentityId id, GuestAccount guestAccount, Date expiryDate, String idNo) {
		this.id = id;
		this.guestAccount = guestAccount;
		this.expiryDate = expiryDate;
		this.idNo = idNo;
	}

	public GuestAccountIdentity(GuestAccountIdentityId id, GuestAccount guestAccount, Date issueDate, String issuePlace,
                                Date expiryDate, String idNo, String idTitle, String idFirstName, String idLastName, String idMiddleName) {
		this.id = id;
		this.guestAccount = guestAccount;
		this.issueDate = issueDate;
		this.issuePlace = issuePlace;
		this.expiryDate = expiryDate;
		this.idNo = idNo;
		this.idTitle = idTitle;
		this.idFirstName = idFirstName;
		this.idLastName = idLastName;
		this.idMiddleName = idMiddleName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unitCode", column = @Column(name = "unit_code", nullable = false, length = 5)),
			@AttributeOverride(name = "guestUid", column = @Column(name = "guest_uid", nullable = false)),
			@AttributeOverride(name = "idType", column = @Column(name = "id_type", nullable = false, length = 3)) })
	public GuestAccountIdentityId getId() {
		return this.id;
	}

	public void setId(GuestAccountIdentityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "guest_uid", nullable = false, insertable = false, updatable = false)
	public GuestAccount getGuestAccount() {
		return this.guestAccount;
	}

	public void setGuestAccount(GuestAccount guestAccount) {
		this.guestAccount = guestAccount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "issue_date", length = 10)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "issue_place", length = 60)
	public String getIssuePlace() {
		return this.issuePlace;
	}

	public void setIssuePlace(String issuePlace) {
		this.issuePlace = issuePlace;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiry_date", nullable = false, length = 10)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "id_no", nullable = false, length = 100)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "id_title", length = 100)
	public String getIdTitle() {
		return this.idTitle;
	}

	public void setIdTitle(String idTitle) {
		this.idTitle = idTitle;
	}

	@Column(name = "id_first_name", length = 100)
	public String getIdFirstName() {
		return this.idFirstName;
	}

	public void setIdFirstName(String idFirstName) {
		this.idFirstName = idFirstName;
	}

	@Column(name = "id_last_name", length = 100)
	public String getIdLastName() {
		return this.idLastName;
	}

	public void setIdLastName(String idLastName) {
		this.idLastName = idLastName;
	}

	@Column(name = "id_middle_name", length = 100)
	public String getIdMiddleName() {
		return this.idMiddleName;
	}

	public void setIdMiddleName(String idMiddleName) {
		this.idMiddleName = idMiddleName;
	}

}
