package com.samasa.hspms.guest.Entity;

import com.samasa.hspms.Booking.validation.Entity.RoomBooking.OcmTrListReservedGuest;
import java.util.Date;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * GuestAccount generated by hbm2java
 */
@Entity
@Table(name = "guest_account", catalog = "hs_pmsm", uniqueConstraints = @UniqueConstraint(columnNames = { "unit_code",
		"guest_ac_type", "guest_uid", "profile_id", "mgd_unit_code", "shared_profile_id" }))
public class GuestAccount implements java.io.Serializable {

	private Integer id;
	private String unitCode;
	private String guestAcType;
	private int guestUid;
	private String profileId;
	private int corpGuestUid;
	private String mgdUnitCode;
	private char sharedProfileId;
	private String title;
	private String titleDesc;
	private String accountName;
	private String firstName;
	private String lastName;
	private String middleName;
	private String salutation;
	private String designation;
	private String occupation;
	private Character gender;
	private String nationality;
	private String domicileCode;
	private Date guestDob;
	private String spouseName;
	private String creditCardType;
	private String creditCardNo;
	private Date creditCardExipry;
	private String activeManagerId;
	private String statusCreditAllowed;
	private String slUid;
	private char statusCashOnly;
	private char statusBlacklist;
	private String guestLngCode;
	private String guestComment;
	private String guestGstVatNumber;
	private char isLoyalty;
	private char guestHistoryType;
	private String htngGuestUid;
	private int crUserUid;
	private Date crDatetime;
	private Integer crSessionId;
	private Integer mfdUserUid;
	private Date mfdDatetime;
	private Integer mfdSessionId;
	private OcmTrListReservedGuest ocmTrListReservedGuest;

	
	public GuestAccount() {
	}

	public GuestAccount(String unitCode, String guestAcType, int guestUid, String profileId, int corpGuestUid,
						String mgdUnitCode, String statusCreditAllowed, char statusCashOnly, char statusBlacklist, char isLoyalty,
						char guestHistoryType, int crUserUid, Date crDatetime) {
		this.unitCode = unitCode;
		this.guestAcType = guestAcType;
		this.guestUid = guestUid;
		this.profileId = profileId;
		this.corpGuestUid = corpGuestUid;
		this.mgdUnitCode = mgdUnitCode;
		this.statusCreditAllowed = statusCreditAllowed;
		this.statusCashOnly = statusCashOnly;
		this.statusBlacklist = statusBlacklist;
		this.isLoyalty = isLoyalty;
		this.guestHistoryType = guestHistoryType;
		this.crUserUid = crUserUid;
		this.crDatetime = crDatetime;
	}

	public GuestAccount(String unitCode, String guestAcType, int guestUid, String profileId, int corpGuestUid,
						String mgdUnitCode, char sharedProfileId, String title, String titleDesc, String accountName,
						String firstName, String lastName, String middleName, String salutation, String designation,
						String occupation, Character gender, String nationality, String domicileCode, Date guestDob,
						String spouseName, String creditCardType, String creditCardNo, Date creditCardExipry,
						String activeManagerId, String statusCreditAllowed, String slUid, char statusCashOnly, char statusBlacklist,
						String guestLngCode, String guestComment, String guestGstVatNumber, char isLoyalty, char guestHistoryType,
						String htngGuestUid, int crUserUid, Date crDatetime, Integer crSessionId, Integer mfdUserUid,
						Date mfdDatetime, Integer mfdSessionId, Set<GuestAccountDefaults> guestAccountDefaultses,
						Set<GuestAccountStats> guestAccountStatses, Set<GuestAccountContacts> guestAccountContactses,
						Set<GuestAccountMembership> guestAccountMemberships,
						Set<GuestAccountDocAttachment> guestAccountDocAttachments,
						Set<GuestAccountIdentity> guestAccountIdentities,
						OcmTrListReservedGuest ocmTrListReservedGuest) {
		this.unitCode = unitCode;
		this.guestAcType = guestAcType;
		this.guestUid = guestUid;
		this.profileId = profileId;
		this.corpGuestUid = corpGuestUid;
		this.mgdUnitCode = mgdUnitCode;
		this.sharedProfileId = sharedProfileId;
		this.title = title;
		this.titleDesc = titleDesc;
		this.accountName = accountName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.salutation = salutation;
		this.designation = designation;
		this.occupation = occupation;
		this.gender = gender;
		this.nationality = nationality;
		this.domicileCode = domicileCode;
		this.guestDob = guestDob;
		this.spouseName = spouseName;
		this.creditCardType = creditCardType;
		this.creditCardNo = creditCardNo;
		this.creditCardExipry = creditCardExipry;
		this.activeManagerId = activeManagerId;
		this.statusCreditAllowed = statusCreditAllowed;
		this.slUid = slUid;
		this.statusCashOnly = statusCashOnly;
		this.statusBlacklist = statusBlacklist;
		this.guestLngCode = guestLngCode;
		this.guestComment = guestComment;
		this.guestGstVatNumber = guestGstVatNumber;
		this.isLoyalty = isLoyalty;
		this.guestHistoryType = guestHistoryType;
		this.htngGuestUid = htngGuestUid;
		this.crUserUid = crUserUid;
		this.crDatetime = crDatetime;
		this.crSessionId = crSessionId;
		this.mfdUserUid = mfdUserUid;
		this.mfdDatetime = mfdDatetime;
		this.mfdSessionId = mfdSessionId;
		this.ocmTrListReservedGuest = ocmTrListReservedGuest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	@Column(name = "unit_code", nullable = false, length = 5)
	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	@Column(name = "guest_ac_type", nullable = false, length = 2)
	public String getGuestAcType() {
		return this.guestAcType;
	}

	public void setGuestAcType(String guestAcType) {
		this.guestAcType = guestAcType;
	}

	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "guest_uid", referencedColumnName = "guest_uid", updatable = false, insertable = false)
	public OcmTrListReservedGuest getOcmTrListReservedGuest() {
		return ocmTrListReservedGuest;
	}

	public void setOcmTrListReservedGuest(OcmTrListReservedGuest ocmTrListReservedGuest) {
		this.ocmTrListReservedGuest = ocmTrListReservedGuest;
	}

	@Column(name = "guest_uid", nullable = false)
	public int getGuestUid() {
		return this.guestUid;
	}

	public void setGuestUid(int guestUid) {
		this.guestUid = guestUid;
	}

	@Column(name = "profile_id", nullable = false, length = 20)
	public String getProfileId() {
		return this.profileId;
	}

	public void setProfileId(String profileId) {
		this.profileId = profileId;
	}

	@Column(name = "corp_guest_uid", nullable = false)
	public int getCorpGuestUid() {
		return this.corpGuestUid;
	}

	public void setCorpGuestUid(int corpGuestUid) {
		this.corpGuestUid = corpGuestUid;
	}

	@Column(name = "mgd_unit_code", nullable = false, length = 5)
	public String getMgdUnitCode() {
		return this.mgdUnitCode;
	}

	public void setMgdUnitCode(String mgdUnitCode) {
		this.mgdUnitCode = mgdUnitCode;
	}

	@Column(name = "shared_profile_id", length = 1)
	public char getSharedProfileId() {
		return this.sharedProfileId;
	}

	public void setSharedProfileId(char sharedProfileId) {
		this.sharedProfileId = sharedProfileId;
	}

	@Column(name = "title", length = 3)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "title_desc", length = 30)
	public String getTitleDesc() {
		return this.titleDesc;
	}

	public void setTitleDesc(String titleDesc) {
		this.titleDesc = titleDesc;
	}

	@Column(name = "account_name", length = 60)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "first_name", length = 60)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 60)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "middle_name", length = 60)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "salutation", length = 60)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "designation", length = 60)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "occupation", length = 60)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "nationality", length = 3)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "domicile_code", length = 3)
	public String getDomicileCode() {
		return this.domicileCode;
	}

	public void setDomicileCode(String domicileCode) {
		this.domicileCode = domicileCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "guest_dob", length = 10)
	public Date getGuestDob() {
		return this.guestDob;
	}

	public void setGuestDob(Date guestDob) {
		this.guestDob = guestDob;
	}

	@Column(name = "spouse_name", length = 60)
	public String getSpouseName() {
		return this.spouseName;
	}

	public void setSpouseName(String spouseName) {
		this.spouseName = spouseName;
	}

	@Column(name = "credit_card_type", length = 4)
	public String getCreditCardType() {
		return this.creditCardType;
	}

	public void setCreditCardType(String creditCardType) {
		this.creditCardType = creditCardType;
	}

	@Column(name = "credit_card_no", length = 20)
	public String getCreditCardNo() {
		return this.creditCardNo;
	}

	public void setCreditCardNo(String creditCardNo) {
		this.creditCardNo = creditCardNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "credit_card_exipry", length = 10)
	public Date getCreditCardExipry() {
		return this.creditCardExipry;
	}

	public void setCreditCardExipry(Date creditCardExipry) {
		this.creditCardExipry = creditCardExipry;
	}

	@Column(name = "active_manager_id", length = 3)
	public String getActiveManagerId() {
		return this.activeManagerId;
	}

	public void setActiveManagerId(String activeManagerId) {
		this.activeManagerId = activeManagerId;
	}

	@Column(name = "status_credit_allowed", nullable = false, length = 1, insertable=false)
	public String getStatusCreditAllowed() {
		return this.statusCreditAllowed;
	}

	public void setStatusCreditAllowed(String statusCreditAllowed) {
		this.statusCreditAllowed = statusCreditAllowed;
	}

	@Column(name = "sl_uid", length = 12)
	public String getSlUid() {
		return this.slUid;
	}

	public void setSlUid(String slUid) {
		this.slUid = slUid;
	}

	@Column(name = "status_cash_only", nullable = false, length = 1, insertable=false)
	public char getStatusCashOnly() {
		return this.statusCashOnly;
	}

	public void setStatusCashOnly(char statusCashOnly) {
		this.statusCashOnly = statusCashOnly;
	}

	@Column(name = "status_blacklist", nullable = false, length = 1, insertable=false)
	public char getStatusBlacklist() {
		return this.statusBlacklist;
	}

	public void setStatusBlacklist(char statusBlacklist) {
		this.statusBlacklist = statusBlacklist;
	}

	@Column(name = "guest_lng_code", length = 3)
	public String getGuestLngCode() {
		return this.guestLngCode;
	}

	public void setGuestLngCode(String guestLngCode) {
		this.guestLngCode = guestLngCode;
	}

	@Column(name = "guest_comment")
	public String getGuestComment() {
		return this.guestComment;
	}

	public void setGuestComment(String guestComment) {
		this.guestComment = guestComment;
	}

	@Column(name = "guest_gst_vat_number", length = 20)
	public String getGuestGstVatNumber() {
		return this.guestGstVatNumber;
	}

	public void setGuestGstVatNumber(String guestGstVatNumber) {
		this.guestGstVatNumber = guestGstVatNumber;
	}

	@Column(name = "IsLoyalty", nullable = false, length = 1, insertable=false)
	public char getIsLoyalty() {
		return this.isLoyalty;
	}

	public void setIsLoyalty(char isLoyalty) {
		this.isLoyalty = isLoyalty;
	}

	@Column(name = "guest_history_type", nullable = false, length = 1, insertable=false)
	public char getGuestHistoryType() {
		return this.guestHistoryType;
	}

	public void setGuestHistoryType(char guestHistoryType) {
		this.guestHistoryType = guestHistoryType;
	}

	@Column(name = "htng_guest_uid", length = 20)
	public String getHtngGuestUid() {
		return this.htngGuestUid;
	}

	public void setHtngGuestUid(String htngGuestUid) {
		this.htngGuestUid = htngGuestUid;
	}

	@Column(name = "cr_user_uid", nullable = false)
	public int getCrUserUid() {
		return this.crUserUid;
	}

	public void setCrUserUid(int crUserUid) {
		this.crUserUid = crUserUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_datetime", nullable = false, length = 19)
	public Date getCrDatetime() {
		return this.crDatetime;
	}

	public void setCrDatetime(Date crDatetime) {
		this.crDatetime = crDatetime;
	}

	@Column(name = "cr_session_id")
	public Integer getCrSessionId() {
		return this.crSessionId;
	}

	public void setCrSessionId(Integer crSessionId) {
		this.crSessionId = crSessionId;
	}

	@Column(name = "mfd_user_uid")
	public Integer getMfdUserUid() {
		return this.mfdUserUid;
	}

	public void setMfdUserUid(Integer mfdUserUid) {
		this.mfdUserUid = mfdUserUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mfd_datetime", length = 19)
	public Date getMfdDatetime() {
		return this.mfdDatetime;
	}

	public void setMfdDatetime(Date mfdDatetime) {
		this.mfdDatetime = mfdDatetime;
	}

	@Column(name = "mfd_session_id")
	public Integer getMfdSessionId() {
		return this.mfdSessionId;
	}

	public void setMfdSessionId(Integer mfdSessionId) {
		this.mfdSessionId = mfdSessionId;
	}

}
