package com.samasa.hspms.guest.Entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GuestAccountMembershipId generated by hbm2java
 */
@Embeddable
public class GuestAccountMembershipId implements java.io.Serializable {

	private String unitCode;
	private int guestUid;
	private String clubMemberType;
	private String clubCode;

	public GuestAccountMembershipId() {
	}

	public GuestAccountMembershipId(String unitCode, int guestUid, String clubMemberType, String clubCode) {
		this.unitCode = unitCode;
		this.guestUid = guestUid;
		this.clubMemberType = clubMemberType;
		this.clubCode = clubCode;
	}

	@Column(name = "unit_code", nullable = false, length = 5)
	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	@Column(name = "guest_uid", nullable = false)
	public int getGuestUid() {
		return this.guestUid;
	}

	public void setGuestUid(int guestUid) {
		this.guestUid = guestUid;
	}

	@Column(name = "club_member_type", nullable = false, length = 3)
	public String getClubMemberType() {
		return this.clubMemberType;
	}

	public void setClubMemberType(String clubMemberType) {
		this.clubMemberType = clubMemberType;
	}

	@Column(name = "club_code", nullable = false, length = 3)
	public String getClubCode() {
		return this.clubCode;
	}

	public void setClubCode(String clubCode) {
		this.clubCode = clubCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GuestAccountMembershipId))
			return false;
		GuestAccountMembershipId castOther = (GuestAccountMembershipId) other;

		return ((this.getUnitCode() == castOther.getUnitCode()) || (this.getUnitCode() != null
				&& castOther.getUnitCode() != null && this.getUnitCode().equals(castOther.getUnitCode())))
				&& (this.getGuestUid() == castOther.getGuestUid())
				&& ((this.getClubMemberType() == castOther.getClubMemberType())
						|| (this.getClubMemberType() != null && castOther.getClubMemberType() != null
								&& this.getClubMemberType().equals(castOther.getClubMemberType())))
				&& ((this.getClubCode() == castOther.getClubCode()) || (this.getClubCode() != null
						&& castOther.getClubCode() != null && this.getClubCode().equals(castOther.getClubCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUnitCode() == null ? 0 : this.getUnitCode().hashCode());
		result = 37 * result + this.getGuestUid();
		result = 37 * result + (getClubMemberType() == null ? 0 : this.getClubMemberType().hashCode());
		result = 37 * result + (getClubCode() == null ? 0 : this.getClubCode().hashCode());
		return result;
	}

}