package com.samasa.hspms.guest.Entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GuestAccountDocAttachmentId generated by hbm2java
 */
@Embeddable
public class GuestAccountDocAttachmentId implements java.io.Serializable {

	private String unitCode;
	private int guestUid;
	private String guestDocType;
	private Date guestDocExpiry;

	public GuestAccountDocAttachmentId() {
	}

	public GuestAccountDocAttachmentId(String unitCode, int guestUid, String guestDocType, Date guestDocExpiry) {
		this.unitCode = unitCode;
		this.guestUid = guestUid;
		this.guestDocType = guestDocType;
		this.guestDocExpiry = guestDocExpiry;
	}

	@Column(name = "unit_code", nullable = false, length = 5)
	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	@Column(name = "guest_uid", nullable = false)
	public int getGuestUid() {
		return this.guestUid;
	}

	public void setGuestUid(int guestUid) {
		this.guestUid = guestUid;
	}

	@Column(name = "guest_doc_type", nullable = false, length = 3)
	public String getGuestDocType() {
		return this.guestDocType;
	}

	public void setGuestDocType(String guestDocType) {
		this.guestDocType = guestDocType;
	}

	@Column(name = "guest_doc_expiry", nullable = false, length = 10)
	public Date getGuestDocExpiry() {
		return this.guestDocExpiry;
	}

	public void setGuestDocExpiry(Date guestDocExpiry) {
		this.guestDocExpiry = guestDocExpiry;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GuestAccountDocAttachmentId))
			return false;
		GuestAccountDocAttachmentId castOther = (GuestAccountDocAttachmentId) other;

		return ((this.getUnitCode() == castOther.getUnitCode()) || (this.getUnitCode() != null
				&& castOther.getUnitCode() != null && this.getUnitCode().equals(castOther.getUnitCode())))
				&& (this.getGuestUid() == castOther.getGuestUid())
				&& ((this.getGuestDocType() == castOther.getGuestDocType())
						|| (this.getGuestDocType() != null && castOther.getGuestDocType() != null
								&& this.getGuestDocType().equals(castOther.getGuestDocType())))
				&& ((this.getGuestDocExpiry() == castOther.getGuestDocExpiry())
						|| (this.getGuestDocExpiry() != null && castOther.getGuestDocExpiry() != null
								&& this.getGuestDocExpiry().equals(castOther.getGuestDocExpiry())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUnitCode() == null ? 0 : this.getUnitCode().hashCode());
		result = 37 * result + this.getGuestUid();
		result = 37 * result + (getGuestDocType() == null ? 0 : this.getGuestDocType().hashCode());
		result = 37 * result + (getGuestDocExpiry() == null ? 0 : this.getGuestDocExpiry().hashCode());
		return result;
	}

}