package com.samasa.hspms.guest.Entity;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UnitGuestAcTypeId generated by hbm2java
 */
@Embeddable
public class UnitGuestAcTypeId implements java.io.Serializable {

	private String unitCode;
	private String guestAcType;

	public UnitGuestAcTypeId() {
	}

	public UnitGuestAcTypeId(String unitCode, String guestAcType) {
		this.unitCode = unitCode;
		this.guestAcType = guestAcType;
	}

	@Column(name = "unit_code", nullable = false, length = 5)
	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	@Column(name = "guest_ac_type", nullable = false, length = 2)
	public String getGuestAcType() {
		return this.guestAcType;
	}

	public void setGuestAcType(String guestAcType) {
		this.guestAcType = guestAcType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UnitGuestAcTypeId))
			return false;
		UnitGuestAcTypeId castOther = (UnitGuestAcTypeId) other;

		return ((this.getUnitCode() == castOther.getUnitCode()) || (this.getUnitCode() != null
				&& castOther.getUnitCode() != null && this.getUnitCode().equals(castOther.getUnitCode())))
				&& ((this.getGuestAcType() == castOther.getGuestAcType())
						|| (this.getGuestAcType() != null && castOther.getGuestAcType() != null
								&& this.getGuestAcType().equals(castOther.getGuestAcType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUnitCode() == null ? 0 : this.getUnitCode().hashCode());
		result = 37 * result + (getGuestAcType() == null ? 0 : this.getGuestAcType().hashCode());
		return result;
	}

}