package com.samasa.hspms.guest.Entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UnitGuestAcType generated by hbm2java
 */
@Entity
@Table(name = "unit_guest_ac_type", catalog = "hs_pmsm", uniqueConstraints = @UniqueConstraint(columnNames = {
		"unit_code", "guest_ac_type", "guest_ac_description", "guest_ac_process_type", "guest_ac_seq_start",
		"guest_ac_seq_end", "guest_ac_nextseq_no" }))
public class UnitGuestAcType implements java.io.Serializable {

	private UnitGuestAcTypeId id;
	private String guestAcDescription;
	private String guestAcProcessType;
	private int guestAcMaxlenth;
	private String guestAcPrefix;
	private String guestAcSuffix;
	private int guestAcSeqStart;
	private int guestAcSeqEnd;
	private int guestAcNextseqNo;

	public UnitGuestAcType() {
	}

	public UnitGuestAcType(UnitGuestAcTypeId id, String guestAcDescription, String guestAcProcessType,
			int guestAcMaxlenth, int guestAcSeqStart, int guestAcSeqEnd, int guestAcNextseqNo) {
		this.id = id;
		this.guestAcDescription = guestAcDescription;
		this.guestAcProcessType = guestAcProcessType;
		this.guestAcMaxlenth = guestAcMaxlenth;
		this.guestAcSeqStart = guestAcSeqStart;
		this.guestAcSeqEnd = guestAcSeqEnd;
		this.guestAcNextseqNo = guestAcNextseqNo;
	}

	public UnitGuestAcType(UnitGuestAcTypeId id, String guestAcDescription, String guestAcProcessType,
			int guestAcMaxlenth, String guestAcPrefix, String guestAcSuffix, int guestAcSeqStart, int guestAcSeqEnd,
			int guestAcNextseqNo) {
		this.id = id;
		this.guestAcDescription = guestAcDescription;
		this.guestAcProcessType = guestAcProcessType;
		this.guestAcMaxlenth = guestAcMaxlenth;
		this.guestAcPrefix = guestAcPrefix;
		this.guestAcSuffix = guestAcSuffix;
		this.guestAcSeqStart = guestAcSeqStart;
		this.guestAcSeqEnd = guestAcSeqEnd;
		this.guestAcNextseqNo = guestAcNextseqNo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unitCode", column = @Column(name = "unit_code", nullable = false, length = 5)),
			@AttributeOverride(name = "guestAcType", column = @Column(name = "guest_ac_type", nullable = false, length = 2)) })
	public UnitGuestAcTypeId getId() {
		return this.id;
	}

	public void setId(UnitGuestAcTypeId id) {
		this.id = id;
	}

	@Column(name = "guest_ac_description", nullable = false, length = 20)
	public String getGuestAcDescription() {
		return this.guestAcDescription;
	}

	public void setGuestAcDescription(String guestAcDescription) {
		this.guestAcDescription = guestAcDescription;
	}

	@Column(name = "guest_ac_process_type", nullable = false, length = 2)
	public String getGuestAcProcessType() {
		return this.guestAcProcessType;
	}

	public void setGuestAcProcessType(String guestAcProcessType) {
		this.guestAcProcessType = guestAcProcessType;
	}

	@Column(name = "guest_ac_maxlenth", nullable = false)
	public int getGuestAcMaxlenth() {
		return this.guestAcMaxlenth;
	}

	public void setGuestAcMaxlenth(int guestAcMaxlenth) {
		this.guestAcMaxlenth = guestAcMaxlenth;
	}

	@Column(name = "guest_ac_prefix", length = 10)
	public String getGuestAcPrefix() {
		return this.guestAcPrefix;
	}

	public void setGuestAcPrefix(String guestAcPrefix) {
		this.guestAcPrefix = guestAcPrefix;
	}

	@Column(name = "guest_ac_suffix", length = 10)
	public String getGuestAcSuffix() {
		return this.guestAcSuffix;
	}

	public void setGuestAcSuffix(String guestAcSuffix) {
		this.guestAcSuffix = guestAcSuffix;
	}

	@Column(name = "guest_ac_seq_start", nullable = false)
	public int getGuestAcSeqStart() {
		return this.guestAcSeqStart;
	}

	public void setGuestAcSeqStart(int guestAcSeqStart) {
		this.guestAcSeqStart = guestAcSeqStart;
	}

	@Column(name = "guest_ac_seq_end", nullable = false)
	public int getGuestAcSeqEnd() {
		return this.guestAcSeqEnd;
	}

	public void setGuestAcSeqEnd(int guestAcSeqEnd) {
		this.guestAcSeqEnd = guestAcSeqEnd;
	}

	@Column(name = "guest_ac_nextseq_no", nullable = false)
	public int getGuestAcNextseqNo() {
		return this.guestAcNextseqNo;
	}

	public void setGuestAcNextseqNo(int guestAcNextseqNo) {
		this.guestAcNextseqNo = guestAcNextseqNo;
	}

}